version: '2'

volumes:
  db-data:
    external: false

services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/db-data

  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'

  app:
    tty: true
    stdin_open: true
    build: .
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db
