version: '2'
services:
  box:
    image: busybox
    volumes:
      - /box

  app:
    tty: true
    stdin_open: true
    build: .
    links:
      - db
      - redis
      - sidekiq
    ports:
      - "3000:3000"
    volumes:
      - '.:/root/uprogress'
    volumes_from:
      - box

  db:
    image: postgres:9.4.5
    ports:
      - "5432"
    volumes:
      - postgres:/var/lib/postgres

  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
    volumes_from:
      - box

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    links:
      - db
      - redis
    volumes:
      - '.:/root/uprogress'
    volumes_from:
      - box

volumes:
  redis:
  postgres:
